version: "3.9"

services:
  fyle_backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: fyle_backend
    command: npm run start:prod
    restart: unless-stopped
    expose:
      - '${APP_PORT}'
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.fyle_backend.rule=Host(`${DOCKER_HOSTNAME}`)"
      - "traefik.http.routers.fyle_backend.entrypoints=websecure"
      - "traefik.http.routers.fyle_backend.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.fyle_backend.middlewares=traefik-compress"
      - "traefik.http.services.fyle_backend.loadbalancer.server.port=${APP_PORT}"

networks:
  traefik:
    external: true